### ISSUE TITLE
bug(scope): unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by zinwelzl** [Security-Tools-Alliance/rengine-ng#108]
### Current Behavior

sudo ./install.sh 
           _   _       _
          | \ | |     (_)
  _ __ ___|  \| | __ _ _ _ __   ___
 | '__/ _ \ . ` |/ _` | | '_ \ / _ \
 | | |  __/ |\  | (_| | | | | |  __/
 |_|  \___|_| \_|\__, |_|_| |_|\___| v2.0.4-jasper
                  __/ |
                 |___/

Before running this script, please make sure Docker is running and you have made changes to the '.env' file.
Changing the postgres username & password from .env is highly recommended.

#########################################################################
Please note that this installation script is only intended for Linux
Only x86_64 platform are supported
#########################################################################

Are you sure you made changes to the '.env' file (y/n)? y
Continuing Installation!

Installing reNgine and its dependencies
=========================================================================

#########################################################################
Installing curl...
/usr/bin/curl
CURL already installed, skipping.

#########################################################################
Installing Docker...
/usr/bin/docker
Docker already installed, skipping.

#########################################################################
Installing Docker Compose
/usr/bin/docker
Docker Compose already installed, skipping.

#########################################################################
Installing make
/usr/bin/make
make already installed, skipping.

#########################################################################
Checking Docker status
Docker is running.

#########################################################################
Installing reNgine, please be patient it could take a while

=========================================================================
Generating certificates and building docker images
=========================================================================
unknown shorthand flag: 'f' in -f
See 'docker --help'.

### Expected Behavior

.

### Steps To Reproduce

.

### Environment

```markdown
- reNgine: .
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
Please fill the environment datas

**Comment by zinwelzl** [comment]
- reNgine: https://github.com/Security-Tools-Alliance/rengine-ng
- OS: WattOS 13
- Python: Python 3.11.2
- Docker Engine: 20.10.24+dfsg1
- Docker Compose: Docker Compose version v2.27.1
- Browser: Firefox

**Comment by psyray** [comment]
Seems your OS base is debian, I will test the install and make a feedback

**Comment by psyray** [comment]
Install works fine on Ubuntu 24.04 LTS.
How did you install Docker ? Snap ?
Docker is buggy with Snap install

Follow this setup to install
https://docs.docker.com/engine/install/debian/

**Comment by psyray** [comment]
@zinwelzl Tested on wattOS 13, everything installs well and reNgine-ng is running fine.
Anyway, with a fresh install, with no docker and docker compose installed, reNgine-ng install.sh has installed the Docker Engine version 26.1.4, and you have the 20.10.24+dfsg1
![image](https://github.com/Security-Tools-Alliance/rengine-ng/assets/1230954/fdd8c3b4-de24-4779-b8b8-7496db0786a5)

Your version is the repository version, which is quite old, please update your Docker version as I recommend in the previous post, then test again.

Issue will be opened for 1 week then I will close it

**Comment by zinwelzl** [comment]
With clean WattOS install, rengine works great.
And it is fast.

Scan screenshot fail with this log. 

Logs for scan #1

python3 /usr/src/github/EyeWitness/Python/EyeWitness.py -f /usr/src/scan_results/ginandjuice.shop/scans/81defeee-2bbd-11ef-91bc-0242ac130004/endpoints_alive.txt -d /usr/src/scan_results/ginandjuice.shop/scans/81defeee-2bbd-11ef-91bc-0242ac130004/screenshots --no-prompt --timeout 10 --threads 40


TERM environment variable not set.
################################################################################
#                                  EyeWitness                                  #
################################################################################
#           Red Siege Information Security - https://www.redsiege.com          #
################################################################################

Starting Web Requests (1 Hosts)
Attempting to screenshot https://ginandjuice.shop
Finished in 34.07110023498535 seconds

**Comment by psyray** [comment]
Ok, 👍 
For Eyewitness, open a new issue
