### ISSUE TITLE
bug(screenshot): screenshot scan fails with errors

### ISSUE THREAD

**Issue by zinwelzl** [Security-Tools-Alliance/rengine-ng#110]
### Current Behavior

Scan screenshot fail, EyeWitness TERM environment variable not set

 screenshot fail with this log. 

Logs for scan

python3 /usr/src/github/EyeWitness/Python/EyeWitness.py -f /usr/src/scan_results/ginandjuice.shop/scans/81defeee-2bbd-11ef-91bc-0242ac130004/endpoints_alive.txt -d /usr/src/scan_results/ginandjuice.shop/scans/81defeee-2bbd-11ef-91bc-0242ac130004/screenshots --no-prompt --timeout 10 --threads 40

TERM environment variable not set.
################################################################################
#                                  EyeWitness                                  #
################################################################################
#           Red Siege Information Security - https://www.redsiege.com          #
################################################################################

Starting Web Requests (1 Hosts)
Attempting to screenshot https://ginandjuice.shop
Finished in 34.07110023498535 seconds

### Expected Behavior

.

### Steps To Reproduce

.

### Environment

```markdown
eNgine: https://github.com/Security-Tools-Alliance/rengine-ng
OS: WattOS 13
Browser: Firefox
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
Can I have the content of the files in the command line ?

**Comment by zinwelzl** [comment]
I deleted this version and VM and will install v2.1.0 this weekend.
Sorry.

**Comment by psyray** [comment]
> I deleted this version and VM and will install v2.1.0 this weekend. Sorry.

Tried to reproduce with no success.
Did you try anothet target ?
Waiting for your feedback on the new setup

**Comment by psyray** [comment]
After more tests, it appears that EyeWitness doesn't work anymore, maybe due to the recent EyeWitness modification on bad URL
https://github.com/Security-Tools-Alliance/rengine-ng/issues/15
https://github.com/Security-Tools-Alliance/rengine-ng/pull/98

Current error is
```
celery-1       | run_command                        | INFO | python3 /usr/src/github/EyeWitness/Python/EyeWitness.py -f /usr/src/scan_results/domain.com/scans/a5c50400-2e17-11ef-9f19-0242ac170004/endpoints_alive.txt -d /usr/src/scan_results/domain.com/scans/a5c50400-2e17-11ef-9f19-0242ac170004/screenshots --no-prompt --timeout 10 --threads 40
celery-1       | run_command                        | WARNING | 4105
celery-1       | run_command                        | INFO | wafw00f -i /usr/src/scan_results/domain.com/scans/a5c50400-2e17-11ef-9f19-0242ac170004/input_endpoints_waf_detection.txt -o /usr/src/scan_results/domain.com/scans/a5c50400-2e17-11ef-9f19-0242ac170004/#213_waf_detection.txt
celery-1       | run_command                        | WARNING | 4106
celery-1       | waf_detection                      | WARNING | Task waf_detection status is SUCCESS
celery-1       | screenshot                         | ERROR | too many values to unpack (expected 6)
celery-1       | Traceback (most recent call last):
celery-1       |   File "/usr/src/app/reNgine/celery_custom_task.py", line 129, in __call__
celery-1       |     self.result = self.run(*args, **kwargs)
celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 1196, in screenshot
celery-1       |     protocol, port, subdomain_name, status, screenshot_path, source_path = tuple(row)
celery-1       | ValueError: too many values to unpack (expected 6)
celery-1       | screenshot                         | WARNING | Task screenshot status is FAILED | Error: ValueError('too many values to unpack (expected 6)')
```

It seems the format returned has changed and need to be fixed ASAP

**Comment by zinwelzl** [comment]
I also get
#########################################################################
Installing Docker...
# Executing docker install script, commit: 6d9743e9656cc56f699a64800b098d5ea5a60020
+ sh -c apt-get update -qq >/dev/null
E: The repository 'https://download.docker.com/linux/debian parrot Release' does not have a Release file.

**Comment by psyray** [comment]
@zinwelzl 
Fixed
Could you test by doing a git checkout of the https://github.com/Security-Tools-Alliance/rengine-ng/tree/fix-110-screenshot-error branch
