### ISSUE TITLE
feat(scope): Can you add Groq API?

### ISSUE THREAD

**Issue by zinwelzl** [Security-Tools-Alliance/rengine-ng#116]
### Expected feature

Hi.

Like I said, tested 2.0.6 and 2.1.0 this weekend, and both work great.
No problem!

Now about LLM.
ollama is very slow on VPS, no GPU.

Can you add Groq API?
https://console.groq.com/docs/models
https://console.groq.com/docs/api-reference#chat
It is free for now, only need registration.

Thanks for great project!

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
Closed in favor of #234
