### ISSUE TITLE
bug(scope):  XSS with Certain Vulnerability in Nuclei

### ISSUE THREAD

**Issue by estebanramos** [Security-Tools-Alliance/rengine-ng#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The XSS Payload attached triggers an Stored XSS with the vulnerability **Keycloak 10.0.0 - 18.0.0 - Cross-Site Scripting**
```
{\"Test<img src=x onerror=alert(document.domain)>\":1}
```

### Expected Behavior

No XSS payloads inside a Vulnerability Description should trigger the actual vulnerability

### Steps To Reproduce

1. Scan a Keycloak Target with 10.00 - 18.00 Version
2. Go to Vulnerabilities 
3. The XSS is Triggered if **Keycloak 10.0.0 - 18.0.0 - Cross-Site Scripting** is found within Nuclei

### Environment

```markdown
- reNgine: 2.0.6
- OS: Ubuntu 11,4.0
- Python: 3.11.8
- Docker Engine: 20.10.13
- Docker Compose: 1.29.2
- Browser: Brave 1.64.116
```

### Anything else?

![vuln1](https://github.com/yogeshojha/rengine/assets/13080250/f24682ff-9238-46af-b834-798d5b995d97)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
Thanks for your report, we will try to sanitize data before displaying it in the UI

**Comment by psyray** [comment]
Could you post the location of the payload, ie: a screen of the developer console showing payload
Thx

**Comment by estebanramos** [comment]
Sure, here it is
![Captura de pantalla 2024-06-25 123040](https://github.com/Security-Tools-Alliance/rengine-ng/assets/13080250/398a304b-3053-427a-9047-0f1fc02bd2a2)

**Comment by psyray** [comment]
Fixed, could you test this PR to validate fix please
