### ISSUE TITLE
bug(scan): fetch_url scan fails when a global custom_header is set

### ISSUE THREAD

**Issue by psyray** [Security-Tools-Alliance/rengine-ng#140]
### Current Behavior

When you set a custom_header globally, the fetch_url scan fails with the error
```
celery-1       | fetch_url                          | WARNING | Running gf on pattern "debug_logic"
celery-1       | fetch_url                          | ERROR | local variable 'host_regex' referenced before assignment
celery-1       | Traceback (most recent call last):
celery-1       |   File "/home/rengine/rengine/reNgine/celery_custom_task.py", line 129, in __call__
celery-1       |     self.result = self.run(*args, **kwargs)
celery-1       |   File "/home/rengine/rengine/reNgine/tasks.py", line 1967, in fetch_url
celery-1       |     cmd = f'cat {self.output_path} | gf {gf_pattern} | grep -Eo {host_regex} >> {gf_output_file}'
celery-1       | UnboundLocalError: local variable 'host_regex' referenced before assignment

```

When you put the custom header inside the fetch_url scan engine config it works

### Expected Behavior

global custom header should not make the fetch_url tasks fails

### Steps To Reproduce

Add a custom header globally in the scan engine and launch a fetch_url task on a target with already scanned subdomains

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

Workaround is to add custom header on each services that support it

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Fixed in https://github.com/Security-Tools-Alliance/rengine-ng/pull/172.
