### ISSUE TITLE
bug(scope): release/2.1.0, can't login to web gui, get this "web-1 | django.server | "GET / HTTP/1.1" 302 0"

### ISSUE THREAD

**Issue by zinwelzl** [Security-Tools-Alliance/rengine-ng#142]
### Current Behavior

redis-1        | 1:M 19 Aug 2024 09:16:40.149 * Background saving terminated with success
web-1          | django.server | "GET / HTTP/1.1" 302 0
web-1          | django.server | "GET / HTTP/1.1" 302 0
web-1          | django.server | "GET / HTTP/1.1" 302 0
web-1          | django.server | "GET / HTTP/1.1" 302 0

### Expected Behavior

web gui don't work, white page

### Steps To Reproduce

version 2.1.0, clean new install

### Environment

```markdown
- reNgine: 2.1.0
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Can you show us a screenshot please?

**Comment by psyray** [comment]
> redis-1 | 1:M 19 Aug 2024 09:16:40.149 * Background saving terminated with success web-1 | django.server | "GET / HTTP/1.1" 302 0 web-1 | django.server | "GET / HTTP/1.1" 302 0 web-1 | django.server | "GET / HTTP/1.1" 302 0 web-1 | django.server | "GET / HTTP/1.1" 302 0

Normal behavior, it's the docker healthcheck

**Comment by zinwelzl** [comment]
prebuilt images works, thanks

**Comment by psyray** [comment]
> prebuilt images works, thanks

There's a little bug with static files path,
Look at this PR #145 and apply it.

It would be merged today

**Comment by AnonymousWP** [comment]
Re-opening this for testing CI (that should automatically close this issue due to it being merged to the release branch).
