### ISSUE TITLE
feat(app): remove .env from index and create .env-dist

### ISSUE THREAD

**Issue by psyray** [Security-Tools-Alliance/rengine-ng#20]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

We should remove **.env** from git index, and create a **.env** template called, for example, **.env-dist**

File is in the **.gitignore** but as the file is in the git index the ignore does not work.

By adding a file **.env-dist**, user can rename it to **.env,** change values and this does not trigger a git change

For more security we could also remove the default password and force user to set it with a strict minimal length and contained chars

**Comment by ocervell** [comment]
I usually use `.env.example` to make it clear what the user has to do.

**Comment by psyray** [comment]
The trick here is to remove from index without deleting the .env file when the user will pull the modification.
Is it possible to do that ?

**Comment by ocervell** [comment]
Probably not... If the .env file has been user modified, it will fail to pull probably. Otherwise it will delete it.

**Comment by psyray** [comment]
Fixed by #139
