### ISSUE TITLE
bug(scope): LLM Toolkit (Beta), can not select downloaded LLM

### ISSUE THREAD

**Issue by zinwelzl** [Security-Tools-Alliance/rengine-ng#212]
### Current Behavior

I can download LLM, in this case qwen, and can see it among others (gpt-3, gpt-4, etc), but can not select it

"Are you sure you want to select this model?
This model will be used to generate Scan Reports and Attack Suggestions."

"Oops! Unable to select the model!"

make logs
proxy-1        | 172.19.0.1 - - [02/Oct/2024:08:33:23 +0000] "PUT /api/tool/ollama/ HTTP/2.0" 200 86 "https://127.0.0.1/scanEngine/default/llm_toolkit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "-"

### Expected Behavior

select llm

### Steps To Reproduce

v 2.1.0
i try 1 and 2 install version, and both don't work

### Environment

```markdown
- reNgine: 2.1.0
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
Could you try again with the latest 2.1.0 version.  (do a `make down; git pull; make up`)
I'm not able to reproduce

**Comment by zinwelzl** [comment]
now work, with last pull
