### ISSUE TITLE
bug(scope): v2.1.0, Container rengine-celery-1  Error 

### ISSUE THREAD

**Issue by zinwelzl** [Security-Tools-Alliance/rengine-ng#219]
### Current Behavior

can't install from source or prebuild

[+] Running 15/15     Created                                                                    ✔ Network rengine_network            Created                                    ✔ Network rengine_network            Created                                                                                                                              0.0s 
 ✔ Volume "rengine_tool_config"       Created                                                                                                                              0.0s  ✔ Volume "rengine_nuclei_templates"  Created                                                                                                                              0.0s 
 ✔ Volume "rengine_gf_patterns"       Created                                                                                                                              0.0s  ✔ Volume "rengine_wordlist"          Created                                                                                                                              0.0s 
 ✔ Volume "rengine_scan_results"      Created                                                                                                                              0.0s  ✔ Volume "rengine_ollama_data"       Created                                                                                                                              0.0s 
 ✔ Volume "rengine_postgres_data"     Created                                                                                                                              0.0s  ✔ Container rengine-redis-1          Healthy                                                                                                                             12.7s 
 ✔ Container rengine-ollama-1         Started                                                                                                                             11.4s  ✔ Container rengine-db-1             Healthy                                                                                                                             25.2s 
 ✘ Container rengine-celery-1         Error                                                                                                                             2779.8s  ✔ Container rengine-celery-beat-1    Created                                                                                                                              0.4s 
 ✔ Container rengine-web-1            Created                                                                                                                              0.1s  ✔ Container rengine-proxy-1          Created                                                                                                                              0.2s 
dependency failed to start: container rengine-celery-1 is unhealthy
make: *** [Makefile:50: up] Error 1
reNgine-ng start failed!

### Expected Behavior

can't install from source or prebuild

### Steps To Reproduce

normal install can't from source or prebuild

### Environment

```markdown
- reNgine: 2.10
- OS: ParrotOS
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Please post logs that are in the Celery container.

**Comment by psyray** [comment]
Parrot OS has not been tested, it's a rolling release, like Kali, which does not work also.
Use Debian or Ubuntu instead, it's a supported one.
Feel free to make it works on ParrotOS and make a feedback on this issue.

**Comment by zinwelzl** [comment]
-------------- celery@query_whois_worker v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.10.11-amd64-x86_64-with-glibc2.36 2024-10-22 10:34:23
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         reNgine:0x7fed2aa47fa0
- ** ---------- .> transport:   redis://redis:6379/0
- ** ---------- .> results:     redis://redis:6379/0
- *** --- * --- .> concurrency: 10 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> query_whois_queue exchange=query_whois_queue(direct) key=query_whois_queue
                

[tasks]
  . crlfuzz_scan
  . dalfox_xss_scan
  . dir_file_fuzz
  . dorking
  . fetch_url
  . geo_localize
  . gpt_vulnerability_description
  . h8mail
  . http_crawl
  . initiate_scan
  . initiate_subscan
  . nmap
  . nuclei_individual_severity_module
  . nuclei_scan
  . osint
  . osint_discovery
  . parse_nmap_results
  . port_scan
  . query_ip_history
  . query_reverse_whois
  . query_whois
  . remove_duplicate_endpoints
  . report
  . run_cmseek
  . run_command
  . run_gf_list
  . run_wafw00f
  . s3scanner
  . screenshot
  . send_file_to_discord
  . send_hackerone_report
  . send_notif
  . send_scan_notif
  . send_task_notif
  . subdomain_discovery
  . theHarvester
  . vulnerability_scan
  . waf_detection

 
 -------------- celery@initiate_scan_worker v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.10.11-amd64-x86_64-with-glibc2.36 2024-10-22 10:34:25
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         reNgine:0x7f36f3d04fa0
- ** ---------- .> transport:   redis://redis:6379/0
- ** ---------- .> results:     redis://redis:6379/0
- *** --- * --- .> concurrency: 30 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> initiate_scan_queue exchange=initiate_scan_queue(direct) key=initiate_scan_queue
                

[tasks]
  . crlfuzz_scan
  . dalfox_xss_scan
  . dir_file_fuzz
  . dorking
  . fetch_url
  . geo_localize
  . gpt_vulnerability_description
  . h8mail
  . http_crawl
  . initiate_scan
  . initiate_subscan
  . nmap
  . nuclei_individual_severity_module
  . nuclei_scan
  . osint
  . osint_discovery
  . parse_nmap_results
  . port_scan
  . query_ip_history
  . query_reverse_whois
  . query_whois
  . remove_duplicate_endpoints
  . report
  . run_cmseek
  . run_command
  . run_gf_list
  . run_wafw00f
  . s3scanner
  . screenshot
  . send_file_to_discord
  . send_hackerone_report
  . send_notif
  . send_scan_notif
  . send_task_notif
  . subdomain_discovery
  . theHarvester
  . vulnerability_scan
  . waf_detection

**Comment by psyray** [comment]
And ?
It works or not ?
I didn't see any errors in your log

**Comment by zinwelzl** [comment]
ParrotOS use Podman, not Docker but some kind of wrapper.
I will remove Podman, (re)install Docker and then try rengine-ng again.
But, not tonight, it is late.

**Comment by zinwelzl** [comment]
i reinstall docker and can run other projects, but still can't rengine-ng

this is output

Certificates have been generated
Pulling pre-built Docker images...
Using: docker-compose
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/docker-compose.yml pull
[+] Running 7/7
 ⠿ db Pulled                                                                                                                                                               0.7s
 ⠿ redis Pulled                                                                                                                                                            0.6s
 ⠿ proxy Pulled                                                                                                                                                            0.7s
 ⠿ celery-beat Pulled                                                                                                                                                      0.7s
 ⠿ ollama Pulled                                                                                                                                                           0.7s
 ⠿ web Pulled                                                                                                                                                              0.7s
 ⠿ celery Pulled                                                                                                                                                           0.7s
Docker images have been pulled
Docker containers starting, please wait as starting the Celery container could take a while...
Using: docker-compose
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/docker-compose.yml up -d db web proxy redis celery celery-beat ollama
[+] Running 0/1
[+] Running 7/8ine_network  Creating                                                                                                                                       0.2s
 ⠿ Network rengine_network          Created                                                                                                                                0.2s
 ⠿ Container rengine-ollama-1       Started                                                                                                                                3.0s
 ⠿ Container rengine-db-1           Healthy                                                                                                                               14.2s
 ⠿ Container rengine-redis-1        Healthy                                                                                                                               14.2s
 ⠿ Container rengine-celery-1       Waiting                                                                                                                             1228.5s
 ⠿ Container rengine-celery-beat-1  Created                                                                                                                                0.1s
 ⠿ Container rengine-web-1          Created                                                                                                                                0.2s
 ⠿ Container rengine-proxy-1        Created                                                                                                                                0.1s
container for service "celery" is unhealthy
make: *** [Makefile:50: up] Error 1
reNgine-ng start failed!

**Comment by psyray** [comment]
Permission issue, for sure.
Have you upgraded from rengine ? Or from reNgine-ng 2.0.7 ?

**Comment by psyray** [comment]
Post `make logs | grep celery` output here
Come to the discord to talk about this it's more efficient.

**Comment by zinwelzl** [comment]
when vm have 12GB RAM or more, installation works
so, it is maybe memory problem

**Comment by psyray** [comment]
> when vm have 12GB RAM or more, installation works so, it is maybe memory problem

Maybe, 16go is recommended, but 8go should work.

**Comment by zinwelzl** [comment]
i will try new parrotos 6.2, yesterday released

**Comment by psyray** [comment]
> i will try new parrotos 6.2, yesterday released

We need testers for other os,
If you could make a detailed feedback of what works or not, with details for process to make it works, we could add it to the wiki

**Comment by zinwelzl** [comment]
works in parrotos 6.2, but first install docker-compose v2 yourself
alot of distros have old docker-compose and that is problem with lot of others projects

**Comment by psyray** [comment]
Ok, it's the only problem with ParrotOS ?
A PR is already related to this, I will finish it ASAP
https://github.com/Security-Tools-Alliance/rengine-ng/pull/211

**Comment by zinwelzl** [comment]
every distro with old compose have problem, but wattOS dont have compose installed, and rengine-ng works great, install compose v2 and run
so, maybe first remove compose v1 and then install v2, that is how i did it, upgrade dont work, for parrotos
