### ISSUE TITLE
bug(scope): scanning stops while running scans on target is list of ips.

### ISSUE THREAD

**Issue by c0ldb00t3r** [Security-Tools-Alliance/rengine-ng#237]
### Current Behavior

the scan stops in the middle and no logs are generated while scanning large IP sets. No screenshot also in the scan results.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/72c003d3-aad7-4d00-9764-f941df16bcd6">

### Expected Behavior

for small no of ips like 10 ips ,  it is able to scan , but it's not able to scan large amount of assets.

### Steps To Reproduce

1. in targets add 100 ip list.
2. scan all the IPs together.
3. The scan will not be completed.

### Environment

```markdown
- reNgine: 2.1.0
- OS: ubuntu 20.04
- Python 3.12.3
- Docker version 27.3.1
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
OK I've tested problems seem to come with IPs only not hostname.
I will fix that ASAP
