### ISSUE TITLE
docs: move documentation to Wiki

### ISSUE THREAD

**Issue by AnonymousWP** [Security-Tools-Alliance/rengine-ng#5]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

At the moment documentation is available in too many places (README, website, etc.), which is confusing and cumbersome to keep up-to-date.  We're planning to move most documentation to the Wiki and for a quick setup we'll use the README.

**Comment by psyray** [comment]
This one could be closed no ?

**Comment by AnonymousWP** [comment]
The current README is quite long, so maybe we should move most of it (except quick install and some basic information) to the Wiki as well.

**Comment by psyray** [comment]
> The current README is quite long, so maybe we should move most of it (except quick install and some basic information) to the Wiki as well.

Yes, could you do it ?

**Comment by AnonymousWP** [comment]
Yep, I will.

**Comment by AnonymousWP** [comment]
To-do:

Move / link to it:

- Contributing
- Screenshots (only keep first one)
- Scan engine
- Submitting issues
- Table of contents
- About reNgine-ng
- Features
- First-time Open Source contributors
- Merge Support with Contributing
- License
- reNgine-ng Bug Bounty Program
