### ISSUE TITLE
feat(docker): Remove installation of deprecated docker-compose

### ISSUE THREAD

**Issue by psyray** [Security-Tools-Alliance/rengine-ng#53]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

The `install.sh` script installs `docker-compose` on the host ([here](https://github.com/yogeshojha/rengine/blob/master/install.sh#L66)). This is also known as Docker Compose v1 and has been deprecated since May 10, 2021. Instead, check if the host is already running v2 - they already have support for `docker compose`:

### Anything else?

Already merged in 2.1.0 release branch

**Comment by AnonymousWP** [comment]
Re-opening this for testing CI (that should automatically close this issue due to it being merged to the release branch).

**Comment by psyray** [comment]
out of date as we have taken the 2 commands into account
