### ISSUE TITLE
feat(version): Rework the version number bump to update it in one place only

### ISSUE THREAD

**Issue by yarysp** [Security-Tools-Alliance/rengine-ng#70]
### Expected feature

Change the version number in one place and version should update everywhere

For now the version should be changed in multiple place, which is not really a good practice.
And a place is frequently forgotten, so there's a version in the UI, another in the docker ...

We need to rethink and rework this part

Ideas are welcome

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Talanor** [comment]
Will do a pr soon, I already have a working version of this
