### ISSUE TITLE
build(install): print URL of reNgine-ng after successful installation

### ISSUE THREAD

**Issue by AnonymousWP** [Security-Tools-Alliance/rengine-ng#85]
### Expected feature

As the title says: it would be welcoming to have the URL of where reNgine-ng runs printed, including the port. Then, users can just open reNgine-ng right from their terminal.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
For this issue, there are multiples cases: 
- The one where the user has filled the domain in the .env and do the stuff for the DNS part
- The one where the user did not configure any domain and use directly ip adress, or an entry in the host, without modifying the env.

So we could display the url based on the .env and also the IP address no ?

**Comment by AnonymousWP** [comment]
Yeah, I just need to think how to do that. It'll be difficult though, because the code itself can't verify whether [domain name] exists or not. It'll get too tricky. Perhaps I'll just do it by IP-address; IP-address always works, DNS only works when configured.
